# -*- coding: utf-8 -*-
"""
Shared profanity word list - curse, sexual, abusive, adultery, f-words, obscene language
Used by both audio_profanity_detector.py and subtitle_processor.py
"""

# Comprehensive profanity list - curse, sexual, abusive, adultery, f-words, obscene language
PROFANITY_WORDS = {
    # =============================================
    # INGLES (se mantiene igual - solo resumen)
    # =============================================
    'fuck', 'fucking', 'fucked', 'fucker', 'fuckers', 'fuckin', 'fucka', 'fuckable', 'fuckass',
    'fuckbag', 'fuckbitch', 'fuckbook', 'fuckboy', 'fuckbrain', 'fuckbuddy', 'fuckbutt', 
    'fuckd', 'fuckedup', 'fuckersucker', 'fuckface', 'fuckfest', 'fuckfreak', 'fuckfriend',
    'fuckhead', 'fuckheads', 'fuckher', 'fuckhole', 'fuckina', 'fuckings', 'fuckingshitmotherfucker', 'motherfucker', 'mother fucker',
    'fuckinnuts', 'fuckinright', 'fuckit', 'fuckknob', 'fuckme', 'fuckmeat', 'fuckmehard',
    'fuckmonkey', 'fuckn', 'fucknugget', 'fucknut', 'fucknuts', 'fucknutt', 'fucknutz',
    'fuckoff', 'fuckpig', 'fuckpuppet', 'fuckr', 'fucks', 'fuckstick', 'fucktard', 'fucktards',
    'fucktoy', 'fucktrophy', 'fuckup', 'fuckwad', 'fuckwhit', 'fuckwhore', 'fuckwit', 'fuckwitt',
    'fuckyomama', 'fuckyou', 'fuk', 'fukah', 'fuken', 'fuker', 'fukin', 'fuking', 'fukk',
    'fukkah', 'fukken', 'fukker', 'fukkin', 'fukking', 'fuks', 'fuktard', 'fuktards',
    'fukwhit', 'fukwit', 'fuuck', 'fux', 'fux0r', 'fuxor', 'fvck', 'fvk', 'fxck',
    'shit', 'shitting', 'shitty', 'shits', 'shitbox', 'shitcan', 'shitdick', 'shite',
    'shiteater', 'shited', 'shitface', 'shitfaced', 'shitfit', 'shitforbrains', 'shitfuck',
    'shitfucker', 'shitfull', 'shithapens', 'shithappens', 'shithead', 'shithouse', 'shiting',
    'shitlist', 'shitola', 'shitoutofluck', 'shitstain', 'shitted', 'shitter', 'bullshit',
    'bullshits', 'bullshitted', 'horseshit',
    'ass', 'asses', 'asshole', 'assholes', 'assbag', 'assbagger', 'assbandit', 'assbang',
    'assbanged', 'assbanger', 'assbangs', 'assbite', 'assblaster', 'assclown', 'asscock',
    'asscowboy', 'asscracker', 'assface', 'assfuck', 'assfucker', 'assfukka', 'assgoblin',
    'assh0le', 'assh0lez', 'asshat', 'asshead', 'assho1e', 'assholz', 'asshopper', 'asshore',
    'assjacker', 'assjockey', 'asskiss', 'asskisser', 'assklown', 'asslick', 'asslicker',
    'asslover', 'assman', 'assmaster', 'assmonkey', 'assmunch', 'assmuncher', 'assnigger',
    'asspacker', 'asspirate', 'asspuppies', 'assrammer', 'assranger', 'assshit', 'assshole',
    'asssucker', 'asswad', 'asswhole', 'asswhore', 'asswipe', 'asswipes', 'azz', 'azzhole',
    'bigass', 'dumbass', 'dumbasses', 'fatass', 'gassyass', 'gayass', 'smartass',
    'bitch', 'bitches', 'bitching', 'bitchass', 'bitched', 'bitcher', 'bitchers', 'bitchez',
    'bitchin', 'bitchslap', 'bitchtit', 'bitchy', 'biteme', 'dumbbitch', 'nastybitch',
    'skankbitch', 'skankybitch',
    'bastard', 'bastards', 'bast', 'bastardo', 'bastardz', 'bassterd', 'bassterds',
    'basterds', 'basterdz', 'bigbastard',
    'crap', 'crappy', 'crapola', 'crapper', 'piss', 'pissing', 'pissed', 'pisser', 'pisses',
    'pisshead', 'pissin', 'pissoff',
    'dick', 'dicks', 'dickhead', 'dick pic', 'dick-ish', 'dickbag', 'dickbeater', 'dickbeaters',
    'dickbrain', 'dickdipper', 'dickface', 'dickflipper', 'dickforbrains', 'dickfuck',
    'dickheads', 'dickhole', 'dickish', 'dickjuice', 'dickless', 'dicklick', 'dicklicker',
    'dickman', 'dickmilk', 'dickmonger', 'dickpic', 'dickripper', 'dicksipper', 'dickslap',
    'dickslicker', 'dicksucker', 'dickwad', 'dickweasel', 'dickweed', 'dickwhipper', 'dickwod',
    'dickzipper', 'pindick', 'limpdick',
    'cock', 'cocks', 'cock-head', 'cock-sucker', 'cockbite', 'cockblock', 'cockblocker',
    'cockburger', 'cockcowboy', 'cockface', 'cockfight', 'cockfucker', 'cockhead', 'cockholster',
    'cockjockey', 'cockknob', 'cockknocker', 'cockknoker', 'cocklicker', 'cocklover',
    'cockmaster', 'cockmongler', 'cockmongruel', 'cockmonkey', 'cockmunch', 'cockmuncher',
    'cocknob', 'cocknose', 'cocknugget', 'cockqueen', 'cockrider', 'cockshit', 'cocksman',
    'cocksmith', 'cocksmoker', 'cocksucer', 'cocksuck', 'cocksucked', 'cocksucker',
    'cocksucking', 'cocksucks', 'cocksuka', 'cocksukka', 'cocktease', 'cocktail', 'cocky',
    'c0ck', 'c0cks', 'c0cksucker', 'c0k', 'cawk', 'cawks', 'cazzo', 'cok', 'cokmuncher',
    'coksucka', 'kock',
    'pussy', 'pussies', 'puss', 'pussie', 'pussycat', 'pussyeater', 'pussyfucker',
    'pussylicker', 'pussylips', 'pussylover', 'pussypounder', 'pusy', 'pu55i', 'pu55y',
    'hotpussy', 'destroyyourpussy',
    'cunt', 'cunts', 'cunteyed', 'cuntface', 'cuntfuck', 'cuntfucker', 'cunthole',
    'cunthunter', 'cuntlick', 'cuntlicker', 'cuntlicking', 'cuntrag', 'cuntslut',
    'cuntsucker', 'cuntz', 'cnut', 'cnts', 'cntz', 'cunilingus', 'cunillingus', 'cunn',
    'cunnie', 'cunnilingus', 'cunntt', 'cunny', 'kunilingus', 'kunnilingus', 'kunt', 'kunts',
    'kuntz',
    'whore', 'whores', 'asswhore', 'crackwhore', 'fuckwhore', 'nastywhore', 'sexwhore',
    'skankwhore', 'skankywhore', 'slutwhore', 'whorefucker', 'whorehouse', 'camwhore',
    'easyslut', 'nastyslut',
    'slut', 'sluts', 'slutt', 'slutting', 'slutty', 'slutwear', 'slutwhore',
    'motherfucker', 'motherfuckers', 'motherfuck', 'motherfucked', 'motherfuckin',
    'motherfucking', 'motherfuckings', 'mothafuck', 'mothafucka', 'mothafuckaz', 'mothafucked',
    'mothafucker', 'mothafuckin', 'mothafucking', 'mothafuckings', 'mofo', 'm0f0', 'm0fo',
    'sperm', 'semen', 'cum', 'cum face', 'cum licker', 'cumbubble', 'cumdumpster', 'cumfest',
    'cumguzzler', 'cuming', 'cumjockey', 'cumlickr', 'cumm', 'cummer', 'cummin', 'cumming',
    'cumquat', 'cumqueen', 'cums', 'cumshot', 'cumshots', 'cumslut', 'cumstain', 'cumsucker',
    'cumtart', 'kum', 'kumbubble', 'kumbullbe', 'kumer', 'kummer', 'kumming', 'kumquat',
    'kums', 'jiz', 'jizim', 'jizin', 'jizjuice', 'jizm', 'jizn', 'jizz', 'jizzd', 'jizzed',
    'jizzim', 'jizzin', 'jizzn', 'jizzum', 'jism', 'jiss', 'jisim',
    'sex', 'sexual', 'sexually', 'sexed', 'sexfarm', 'sexhound', 'sexhouse', 'sexing',
    'sexkitten', 'sexpot', 'sexslave', 'sextogo', 'sextoy', 'sextoys', 'sexwhore', 'sexy',
    'sexymoma', 'sexy-slim', 'cybersex', 'gay sex', 'gaysex', 'group sex',
    'hardcoresex', 'hotsex', 'livesex', 'phonesex',
    'porn', 'pornography', 'pornographic', 'pornflick', 'pornking', 'porno', 'pornprincess',
    'nude', 'naked', 'nudity', 'nudger', 'barenaked',
    'orgasm', 'orgasmic', 'orga', 'orgasim', 'orgies', 'orgy', 'goregasm',
    'masturbat', 'masturbation', 'masturbating', 'm45terbate', 'ma5terb8', 'ma5terbate',
    'massterbait', 'masstrbait', 'masstrbate', 'mastabate', 'mastabater', 'master-bate',
    'masterb8', 'masterbaiter', 'masterbat', 'masterbat3', 'masterbate', 'masterblaster',
    'mastrabator', 'beatoff', 'beatyourmeat', 'jerk off', 'jerk-off', 'jerk0ff', 'jerked',
    'jerkoff', 'j3rk0ff', 'jack off', 'jack-off', 'jackoff', 'smackthemonkey', 'spankthemonkey',
    'ejaculat', 'ejaculation', 'ejackulate', 'ejakulate',
    'penis', 'vagina', 'genital', 'genitals', 'peni5', 'penile', 'penises', 'vaginal',
    'breast', 'breasts', 'boob', 'boobs', 'boobies', 'booby', 'b00b', 'b00bies', 'b00biez',
    'b00bs', 'b00bz', 'booobs', 'boooobs', 'booooobs', 'booooooobs', 'brea5t', 'breastjob',
    'breastlover', 'breastman', 'big breasts', 'big knockers', 'big tits', 'bigbreasts',
    'bigtits', 'bitties', 'dirty pillows', 'headlights', 'knockers', 'mams', 'tits', 'titties',
    'tit', 'titbitnipply', 'titfuck', 'titfucker', 'titfuckin', 'titjob', 'titlicker',
    'titlover', 'titty', 'tittie',
    'butt', 'buttock', 'buttocks', 'butt plug', 'butt-pirate', 'buttbang', 'buttcheeks',
    'buttface', 'buttfuck', 'buttfucker', 'buttfuckers', 'butthead', 'butthole', 'buttman',
    'buttmuch', 'buttmunch', 'buttmuncher', 'buttpirate', 'buttplug', 'buttstain', 'buttwipe',
    'bigbutt', 'rearend', 'rump',
    'nipple', 'nipplering', 'nipples', 'clit', 'clitface', 'clitfuck', 'clits', 'clitty', 'cl1t', 'clitoris',
    'labia', 'hymen', 'rectum', 'anus', 'scrotum', 'teste', 'testicle', 'testicles', 'gonad', 'gonads',
    'glans', 'foreskin', 'crotch', 'crotchjockey', 'crotchmonkey', 'crotchrot', 'groin',
    'kiss', 'kissing', 'kissed', 'kisses', 'kissass', 'smooch', 'makeout',
    'foreplay', 'intimate', 'intimacy',
    'lovemaking', 'make love', 'making love', 'getiton', 'laid',
    'intercourse', 'sexual intercourse', 'coital', 'coitus', 'copulate', 'fornicate',
    'oral sex', 'anal sex', 'analsex', 'anilingus', 'cunnilingus', 'fellatio', 'felatio',
    'felch', 'felcher', 'felching', 'fellate', 'feltch', 'feltcher', 'feltching',
    'deep throat', 'deep throating', 'deapthroat', 'deepthroat', 'deepthroating',
    'blow j', 'blow job', 'blow your l', 'blow your load', 'blowjob', 'blowjobs', 'givehead',
    'hand job', 'handjob', 'footjob', 'rimjob', 'rimming',
    'moan', 'moaning', 'groan', 'groaning', 'pant', 'panting', 'gasp', 'gasping',
    'scream', 'screaming', 'heavy breathing', 'heavybreath', 'heavybreathing',
    'whispering', 'licking',
    'female squirting', 'femalesquirtin', 'femalesquirting', 'male squirting', 'squirting',
    'erotic', 'erotica', 'eroticism', 'ero', 'earotics', 'auto erotic', 'autoerotic', 'sensual', 'steamy', 'salacious',
    'bondage', 'bdsm', 'dominatricks', 'dominatrics', 'dominatrix', 'dommes', 'masochist',
    'masokist', 'sadis', 'sadom', 'fetish', 'fetishism', 'kinky', 'foot fetish', 'footaction', 'footfetish',
    'footfuck', 'footfucker', 'footlicker', 'footstar',
    'seduce', 'seduction', 'seductive', 'seducing',
    'lust', 'lustful', 'lusty', 'lusting', 'craving', 'desire', 'temptation', 'tempted', 'tempting', 'enticing', 'alluring', 'inviting',
    'aroused', 'arousal', 'passionate', 'passion', 'chemistry', 'infatuation',
    'bedroom', 'shower scene', 'bath scene',
    'stripper', 'stripping', 'strip club', 'stripclub', 'strip', 'striptease',
    'lingerie', 'underwear', 'bra', 'panties', 'panti', 'gstring', 'thong', 'skimpy', 'revealing', 'cleavage',
    'topless', 'bottomless', 'unclothed', 'exposed', 'undress', 'undressing', 'unzip', 'unbutton',
    'suggestive', 'suggestively', 'provocative',
    'flirt', 'flirting', 'flirtatious', 'flirty', 'flirtation',
    'threesome', 'threeway', 'foursome', 'gang bang', 'gangbang', 'gangbanged', 'gangbanger',
    'gangbangs', 'double penetration', 'doublepenetration', 'dp action', 'dpaction',
    'bareback', 'barely legal', 'barelylegal',
    'creamy', 'creampie', 'pearlnecklace', 'golden shower', 'goldenshower', 'brown shower',
    'brown showers',
    'dog style', 'dog-fucker', 'doggie style', 'doggie', 'doggie-style', 'doggiestyle',
    'doggin', 'dogging', 'doggy style', 'doggy-style', 'doggystyle', 'dawgie style', 'doggy',
    'dawgie-style', 'missionary', 'cowgirl',
    'dildo', 'dildos', 'dild0', 'dild0s', 'd1ld0', 'd1ldo', 'dilld0', 'dilld0s',
    'vibr', 'vibrater', 'vibrator', 'bullet vibe', 'magicwand',
    'fingerbang', 'fingerfood', 'fingerfuck', 'fingerfucked', 'fingerfucker', 'fingerfuckers',
    'fingerfucking', 'fingerfucks', 'fingering',
    'fisted', 'fister', 'fistfuck', 'fistfucked', 'fistfucker', 'fistfuckers', 'fistfucking',
    'fistfuckings', 'fistfucks', 'fisting', 'fisty',
    'frotting', 'spank', 'thrust', 'thrusting', 'grinding', 'grind', 'twerking', 'mounting', 'lapdance',
    'touching', 'caress', 'caressing', 'stroking', 'fondling', 'rubbing',
    'queef', 'wetspot', 'soaked', 'slippery',
    'cheat', 'cheating', 'cheater', 'adultery', 'adulterous', 'affair', 'infidelity',
    'unfaithful', 'betrayal', 'betray', 'mistress', 'lover', 'fling', 'hookup',
    'turd', 'poop', 'pooper', 'pooperscooper', 'pooping', 'dookie', 'doodoo', 'caca',
    'fart', 'farted', 'farting', 'fartknocker', 'farty', 'flatulence',
    'piss', 'pissing', 'pissed', 'pisser', 'pisses', 'pisshead', 'pissin', 'pissoff',
    'pee', 'peehole', 'pee-pee',
    'queer', 'queers', 'fag', 'fag1t', 'fagbag', 'faget', 'fagfucker', 'fagg', 'fagg1t',
    'fagged', 'fagging', 'faggit', 'faggitt', 'faggot', 'faggotcock', 'faggs', 'fagit',
    'fagot', 'fagots', 'fags', 'fagt', 'fagtard', 'fagz', 'faig', 'faigs', 'faigt',
    'dyke', 'dykes', 'dike', 'lesbain', 'lesbayn', 'lesbin', 'lesbo', 'lesbos', 'lez',
    'lezbe', 'lezbefriends', 'lezbian', 'lezbians', 'lezbo', 'lezbos', 'lezz', 'lezzian',
    'lezzie', 'lezzies', 'lezzo', 'lezzy', 'bulldike', 'bulldyke', 'butchbabes', 'butchdike',
    'butchdyke', 'dixiedike', 'dixiedyke',
    'homo', 'hom0', 'h0m0', 'h0mo', 'homobangers', 'homodumbshit', 'homoey',
    'trannie', 'tranny', 'transexual', 'transsexual', 'transvestite', 'trisexual',
    'sissy', 'pansies', 'pansy',
    'prostitute', 'hooker', 'hookers', 'brothel', 'redlight', 'escort', 'escorting',
    'prostitution',
    'camgirl', 'camboy',
    'milf', 'dilf',
    'nasty', 'nastyho', 'naughty', 'dirty',
    'skank', 'skankfuck', 'skanky',
    'slime', 'slimeball', 'slimebucket',
    'smut',
    'snatch', 'snatchpatch',
    'suck', 'suckdick', 'sucker', 'suckme', 'suckmyass', 'suckmydick', 'suckmytit',
    'suckoff', 'corksucker', 'cocksuck', 'cocksucked', 'cocksucker', 'cocksucking',
    'cocksucks', 'cocksuka', 'cocksukka',
    'swallow', 'swallower', 'swalow',
    'twat', 'twink', 'twinkie',
    'wank', 'wanker', 'wanking', 'williewanker',
    'boner', 'boners', 'hardon', 'stiffy', 'wood', 'woody', 'bulge', 'throbbing',
    'horny', 'horney', 'horniest', 'horndawg', 'horndog',
    'libido', 'lusting', 'lusty',
    'booty',
    'randy',
    'turned on', 'turnon',
    'wetb', 'wetback',
    'climax', 'climaxed', 'climaxing', 'pleasure', 'pleasurable',
    'premature',
    'virgin', 'virginbreaker',
    'condom', 'trojan',
    'lubejob', 'lotion',
    'livesex', 'peepshow', 'peepshpw',
    'hentai', 'ecchi', 'futanari', 'futanary',
    'lolita',
    'taboo',
    'xxx',
    'adult', 'mature', 'explicit', 'obscene', 'graphic', 'indecent', 'lewd', 'scandalous', 'spicy',
    'sucking', 'nibble', 'nibbling', 'tease', 'teasing',
    'sext', 'sexting',
    'prick', 'prickhead', 'pric',
    'pube', 'pubic', 'pubiclice',
    'pud', 'pudboy', 'pudd', 'puddboy',
    'puke',
    'quim',
    'schlong',
    'screw', 'screwyou',
    'shag', 'shaggin', 'shagging',
    'shat',
    'spunk', 'spunky',
    'stiffy',
    'strapon',
    'stroke', 'stroking',
    'tampon',
    'tinkle',
    'tongue', 'tongethruster', 'tonguethrust', 'tonguetramp',
    'turd',
    'upskirt',
    'vulva',
    'willy', 'willie',
    'weewee', 'weenie',
    'douche', 'douche bag', 'douche-fag', 'douchebag', 'douchebags', 'douchewaffle', 'douchey',
    'd0uch3', 'd0uche', 'douch3', 'duche',
    'dipshit', 'dipstick', 'dipship',
    'dumb', 'dumbass', 'dumbasses', 'dumbbitch', 'dumbfuck', 'dumbshit', 'dumshit',
    'dumass',
    'fugly', 'mafugly',
    'gob',
    'gook', 'gook eye', 'gook eyes', 'gookeye', 'gookeyes', 'gookies', 'gooks', 'gooky',
    'g00k',
    'hobag',
    'ho', 'hoare', 'hoer', 'hoes', 'hoor', 'hoore', 'hore', 'h00r', 'h0ar', 'h0r', 'h0re',
    'jackass', 'jackhole', 'jackshit',
    'jerk', 'jerries', 'jerry',
    'knob', 'knobbing', 'knobead', 'knobed', 'knobend', 'knobhead', 'knobjocky', 'knobjokey',
    'knobz',
    'lowlife',
    'moron',
    'muff', 'muffdive', 'muffdiver', 'muffindiver', 'mufflikcer',
    'perv',
    'pimp', 'pimped', 'pimper', 'pimpjuic', 'pimpjuice', 'pimpsimp', 'popimp',
    'poon', 'poontang', 'puntang',
    'prick', 'prickhead', 'pric',
    'pube', 'pubic', 'pubiclice',
    'pud', 'pudboy', 'pudd', 'puddboy',
    'puke',
    'queer', 'queers',
    'quim',
    'schlong',
    'screw', 'screwyou',
    'shag', 'shaggin', 'shagging',
    'shat',
    'skank', 'skankfuck', 'skanky',
    'slime', 'slimeball', 'slimebucket',
    'smut',
    'snatch', 'snatchpatch',
    'snot',
    'spunk', 'spunky',
    'suck', 'suckdick', 'sucker', 'suckme', 'suckmyass', 'suckmydick', 'suckmytit',
    'suckoff',
    'swallow', 'swallower', 'swalow',
    'tampon',
    'tinkle',
    'tongue', 'tongethruster', 'tonguethrust', 'tonguetramp',
    'turd',
    'twat', 'twink', 'twinkie',
    'upskirt',
    'vulva',
    'wank', 'wanker', 'wanking', 'williewanker',
    'willy', 'willie',
    'weewee', 'weenie',

    # =====================================================
    # ESPANOL - MEXICANO COMPLETO (sin acentos)
    # =====================================================
    'chinga', 'chingas', 'chingada', 'chingado', 'chingaderas', 'chingaquedito',
    'chingar', 'chingarse', 'chingue', 'chingues', 'chingon', 'chingona', 'chingonerias',
    'chingadazo', 'chingaste',
    'pinche', 'pinches', 'pinche guey', 'pinche viejo', 'pinche vieja',
    'verga', 'vergas', 'vergon', 'vergona', 'verguiza', 'a la verga', 'ala verga',
    'cabron', 'cabrona', 'cabroncito', 'cabroncita', 'cabronada', 'cabronazo',
    'pendejo', 'pendeja', 'pendejada', 'pendejear', 'pendejito', 'pendejita', 'pendejez',
    'mamon', 'mamona', 'mamada', 'mamar', 'mamadera', 'mamazon',
    'culero', 'culera', 'culerada', 'culazo',
    'cagar', 'cagada', 'cagadera', 'cagon', 'cagona', 'cagadero',
    'joto', 'jota', 'maricon', 'marica', 'maricona',
    'zorra', 'zorro', 'perra', 'perro',
    'puta', 'puto', 'putita', 'putazo', 'puteria', 'putear', 'puteado', 'puteando',
    'putamadre', 'putaculo', 'putahermana', 'putamierda', 'putiza', 'putisa',
    'huevon', 'huevona', 'huevones', 'huevonas', 'hueva', 'huevada',
    'chichis', 'chiches', 'tetas', 'tetotas', 'tetona',
    'pito', 'pitito', 'pitote', 'pene',
    'nalgas', 'nalgon', 'nalgona',
    'panocha', 'panoche', 'panchita',
    'chocha', 'chochita',
    'papaya',
    'cojones', 'cojonudo', 'cojon',
    'joder', 'jodido', 'jodiendo', 'joderse',
    'hostia', 'ostia', 'gilipollas', 'capullo',
    'mierda', 'mierdero', 'mierdoso', 'mierdita',
    'culo', 'culito', 'culazo',
    'pedo', 'pedorro', 'pedorrera',
    'sorete', 'orto', 'ojete',
    'caca',
    'cogelon', 'cogelona',
    'ahuevado', 'ahuevada',
    'chingueton', 'chinguetona',
    # NUEVAS (Darkas)
    'carajo', 'imbecil', 'farsa', 'puerca', 'salchicha', 'asesina',

    # =====================================================
    # ESPANOL - VERSIONES CON ACENTO
    # =====================================================
    'cabrón', 'cabróna', 'cabroncito', 'cabroncita', 'cabronada', 'cabronazo',
    'pendejó', 'pendejá', 'pendejada', 'pendejear', 'pendejito', 'pendejita', 'pendejez',
    'chingón', 'chingona', 'chingonerias', 'chingaquedito', 'chingadazo', 'chingaste',
    'mamón', 'mamona', 'mamada', 'mamar', 'mamadera', 'mamazon',
    'culero', 'culera', 'culerada', 'culazo',
    'cagón', 'cagona', 'cagadero',
    'maricón', 'maricona', 'marica',
    'zorra', 'zorro', 'perra', 'perro',
    'puta', 'puto', 'putita', 'putazo', 'puteria', 'putear', 'puteado', 'puteando', 'putó',
    'putamadre', 'putaculo', 'putahermana', 'putamierda', 'putiza',
    'huevón', 'huevona', 'huevones', 'huevonas', 'hueva', 'huevada',
    'tetas', 'tetotas', 'tetona',
    'pito', 'pitito', 'pitote', 'pene', 'pyto', 'píto',
    'nalgas', 'nalgón', 'nalgona',
    'panocha', 'panoche', 'panchita',
    'chocha', 'chochita',
    'cojones', 'cojonudo', 'cojon',
    'jodido', 'jodiendo', 'joderse',
    'hostia', 'ostia', 'gilipollas', 'capullo',
    'mierda', 'mierdero', 'mierdoso', 'mierdita',
    'culo', 'culito', 'culazo',
    'pedo', 'pedorro', 'pedorrera',
    'sorete', 'orto', 'ojete',
    'caca',
    'cogelón', 'cogelona',
    'ahuevado', 'ahuevada',
    'chinguetón', 'chinguetona',
    # NUEVAS CON ACENTO (Darkas)
    'imbécil', 'puerca', 'carajo',

    # Verbos y acciones sexuales
    'coger', 'cogida', 'cogido', 'cogiendo', 'cogemos', 'coges', 'coge',
    'follar', 'follada', 'follado', 'follando', 'follamos', 'follas', 'folla',
    'chupar', 'chupada', 'chupado', 'chupando', 'chupamos', 'chupas', 'chupa',
    'jalar', 'jalada', 'jalado', 'jalando',
    'mamar', 'mamada', 'mamado', 'mamando', 'mamamos', 'mamas', 'mama',
    'culiar', 'culiada', 'culiado', 'culiando', 'culiamos', 'culias', 'culia',

    # Terminos despectivos adicionales
    'naco', 'nacada', 'indio', 'indiota', 'pelado', 'peladito',
    'chota', 'chotas', 'fresón', 'fresa', 'mirrey', 'junior',
    'pitufo', 'baboso', 'babosa', 'ratero', 'ladrón', 'ladrona',
    'puerco', 'cerdo', 'chancho',

    # =====================================================
    # FRASES COMPLETAS (sin acentos)
    # =====================================================
    'chinga tu madre', 'chingue tu madre', 'chinga su madre', 'chingue su madre',
    'vete a la chingada', 'vete a la verga', 'vete al carajo', 'vete a la mierda',
    'vayanse a la mierda', 'vayanse a la verga',
    'me vale verga', 'me vale madre', 'me vale pito', 'me vale cacahuate',
    'no mames', 'no manches', 'no mames guey', 'no manches guey', 'ni mames',
    'ni madres', 'ni mergas',
    'que pendejo', 'que pendeja', 'que cabron', 'que cabrona', 'que chingados',
    'que chingado', 'que chingada', 'que huevon', 'que huevona', 'que huevada',
    'pinche guey', 'pinche viejo', 'pinche vieja', 'pinche pendejo',
    'hijo de puta', 'hija de puta', 'hijueputa', 'hijodeputa',
    'puta madre', 'tu puta madre', 'su puta madre',
    'la chingada', 'a la chingada', 'ta madre',
    'chingado', 'chingada', 'chingadera',
    'me cago en tu madre', 'me cago en todo',
    'te voy a matar', 'te mato', 'te parto la madre', 'te rompo la madre',
    'que te jodan', 'que te follen', 'que te den',
    'vale madre', 'vale verga', 'vale pito',
    'coger con', 'cogiendo con', 'cogida con',
    'follar con', 'follando con', 'follada con',
    'mamar con', 'mamando con', 'mamada con',
    'chupar con', 'chupando con', 'chupada con',
    'jalar el ganso', 'jalar la verga', 'jalar el pescuezo',
    'venirse', 'acabar', 'acabada',
    'correrse', 'corrida', 'corrido',
    'mojar la canoa', 'mojar el churro',
    'hacer el delicioso', 'hacer el amor',
    'sexo oral', 'analsex',
    'chupame el pito', 'chupamela', 'chupamelo',
    'te agarro el pito', 'te agarro la choya', 'te agarro la pata',
    'poner una putiza', 'dar una putiza',
    'hacer bolita', 'hacer papilla',
    'corretear como perro',
    # NUEVAS FRASES (Darkas)
    'a la puta chingada', 'puta chingada', 'pinche salchicha',
    'pendeja bola de cristal', 'ir mucho a la verga', 'como carajo',
    'imbecil de mierda', 'estupido imbecil', 'porca asesina', 'puerca asesina'
}